Repository redhat-appstudio/application-service, pull requests merged in 2022-07, with the labels that each got.

#143 pull in latest alizer
  go.mod
  go.sum
Labels: lgtm

#144 [DEVHAS-134] Sanitize Git error messages
  controllers/component_controller.go
  controllers/component_controller_finalizer.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: lgtm

#145 Use the Component revision
  gitops/generate_build.go
  gitops/generate_build_test.go
Labels: lgtm

#134 [DEVHAS-101] Application Service Binding Controller
  Makefile
  PROJECT
  bundle/manifests/application-service-manager-rolebinding-appsnapshot_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/application-service.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  config/rbac/role_appsnapshot.yaml
  config/rbac/role_binding.yaml
  config/samples/binding/binding.yaml
  config/samples/snapshot/snapshot.yaml
  controllers/applicationsnapshotenvironmentbinding_controller.go
  controllers/applicationsnapshotenvironmentbinding_controller_conditions.go
  controllers/applicationsnapshotenvironmentbinding_controller_test.go
  controllers/component_controller.go
  controllers/component_controller_finalizer.go
  controllers/suite_test.go
  gitops/generate.go
  gitops/generate_test.go
  gitops/gitops.go
  gitops/gitops_test.go
  gitops/resources/kustomization.go
  gitops/resources/kustomization_test.go
  go.mod
  go.sum
  hack/pull-appstudio-shared-and-regen.sh
  main.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: lgtm

#149 Command 'make build' not downloading dependencies.
  Makefile
Labels: lgtm, ok-to-test

#139 [DEVHAS-106] Add SkipGitOpsResourceGeneration field
  api/v1alpha1/component_types.go
  config/crd/bases/appstudio.redhat.com_componentdetectionqueries.yaml
  config/crd/bases/appstudio.redhat.com_components.yaml
  config/kcp/apiexport_has.yaml
  config/kcp/apiresourceschema_has.yaml
  controllers/applicationsnapshotenvironmentbinding_controller.go
  controllers/applicationsnapshotenvironmentbinding_controller_conditions.go
  controllers/applicationsnapshotenvironmentbinding_controller_test.go
  controllers/component_controller.go
  controllers/component_controller_conditions.go
  controllers/component_controller_finalizer_test.go
  controllers/component_controller_test.go
Labels: lgtm

#154 Do not add `appstudio` pvc to gitops
  gitops/generate.go
  gitops/generate_build.go
  gitops/generate_test.go
  gitops/gitops.go
  gitops/testutils/testutils.go
Labels: lgtm

#152 [DEVHAS-100] Add watch support for Environment CR with the Binding controller
  bundle/manifests/application-service.clusterserviceversion.yaml
  bundle/manifests/appstudio.redhat.com_componentdetectionqueries.yaml
  bundle/manifests/appstudio.redhat.com_components.yaml
  config/manager/kustomization.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  config/rbac/role_appsnapshot.yaml
  config/rbac/role_binding.yaml
  config/samples/binding/binding.yaml
  config/samples/environment/environment.yaml
  controllers/applicationsnapshotenvironmentbinding_controller.go
  controllers/applicationsnapshotenvironmentbinding_controller_test.go
  controllers/mapper.go
  controllers/mapper_test.go
  gitops/generate.go
  gitops/generate_test.go
  gitops/gitops.go
  gitops/gitops_test.go
Labels: lgtm

#151 [DEVHAS-109] custom kustomization patch
  gitops/generate.go
  gitops/generate_test.go
  gitops/gitops.go
  gitops/gitops_test.go
  gitops/resources/kustomization.go
  gitops/resources/kustomization_test.go
  gitops/yaml/resources.go
  gitops/yaml/resources_test.go
Labels: lgtm

#159 blow away base folder when generate component
  controllers/component_controller.go
  gitops/gitops.go
  gitops/gitops_test.go
Labels: lgtm

#156 Added ppc64le support
  .github/workflows/build.yml
  Dockerfile
Labels: lgtm, needs-ok-to-test
