Repository redhat-appstudio/application-service, pull requests merged in 2022-04, with the labels that each got.

#85 Add push event for Pipeline as Code
  .tekton/push.yaml
Labels: do-not-merge/work-in-progress, needs-ok-to-test

#86 Clean up old CDQ resources when they are requeued
  controllers/componentdetectionquery_controller.go
  controllers/componentdetectionquery_controller_conditions.go
  controllers/componentdetectionquery_controller_test.go
  pkg/devfile/detect_test.go
  pkg/util/util_test.go
Labels: lgtm

#93 update has to use PVC instead of volumeClaimTemplate
  .tekton/pull-request.yaml
  .tekton/push.yaml
Labels: lgtm

#95 Remove releaseStrategy field from component CRD
  api/v1alpha1/component_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/appstudio.redhat.com_componentdetectionqueries.yaml
  bundle/manifests/appstudio.redhat.com_components.yaml
  config/crd/bases/appstudio.redhat.com_componentdetectionqueries.yaml
  config/crd/bases/appstudio.redhat.com_components.yaml
Labels: lgtm, ok-to-test

#94 [DEVHAS-94] Requeue the Component when its Application can't be found
  controllers/component_controller.go
  controllers/component_controller_test.go
Labels: lgtm

#92 [DEVHAS-26] feat: Support container image components
  api/v1alpha1/component_types.go
  api/v1alpha1/componentdetectionquery_types.go
  config/crd/bases/appstudio.redhat.com_componentdetectionqueries.yaml
  config/crd/bases/appstudio.redhat.com_components.yaml
  controllers/component_controller.go
  controllers/component_controller_test.go
  controllers/componentdetectionquery_controller.go
  controllers/componentdetectionquery_controller_test.go
  controllers/update.go
  controllers/update_test.go
  gitops/generate.go
  gitops/generate_test.go
  pkg/devfile/devfile.go
  pkg/devfile/devfile_test.go
Labels: lgtm

#89 [DEVHAS-85] Add Dockerfile Support for CDQ
  README.md
  api/v1alpha1/component_types.go
  bundle/manifests/appstudio.redhat.com_componentdetectionqueries.yaml
  bundle/manifests/appstudio.redhat.com_components.yaml
  config/crd/bases/appstudio.redhat.com_componentdetectionqueries.yaml
  config/crd/bases/appstudio.redhat.com_components.yaml
  config/samples/application/app.yaml
  controllers/component_controller.go
  controllers/component_controller_test.go
  controllers/componentdetectionquery_controller.go
  controllers/componentdetectionquery_controller_test.go
  controllers/update.go
  controllers/update_test.go
  go.mod
  go.sum
  pkg/devfile/detect.go
  pkg/devfile/detect_test.go
  pkg/devfile/devfile.go
  pkg/devfile/devfile_test.go
  pkg/devfile/errors.go
  pkg/devfile/errors_test.go
  pkg/devfile/utils.go
  pkg/devfile/utils_test.go
  pkg/spi/spi.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: lgtm, ok-to-test

#97 [DEVHAS-87] Add parent kustomize file to gitops repositories
  controllers/component_controller.go
  gitops/generate.go
  gitops/generate_test.go
  gitops/gitops.go
  gitops/gitops_test.go
  gitops/resources/kustomization.go
  gitops/resources/kustomization_test.go
  pkg/github/github.go
Labels: lgtm

#98 Put common-storage-pvc at application-level in gitops repository
  controllers/component_controller.go
  gitops/generate.go
  gitops/generate_build.go
  gitops/generate_test.go
Labels: lgtm

#99 Add context attribute to Application devfiles by deafult
  pkg/devfile/devfile.go
  pkg/devfile/devfile_test.go
Labels: lgtm

#102 Use e2e installation script to install e2e framework and pair PR
  .ci/oci-e2e-has.sh
Labels: lgtm

#100 Add new tests for dockerfile
  controllers/application_controller_test.go
  controllers/component_controller_test.go
  controllers/componentdetectionquery_controller_test.go
  pkg/devfile/detect.go
  pkg/devfile/detect_mock.go
  pkg/devfile/detect_test.go
  pkg/devfile/devfile_test.go
  pkg/devfile/errors_test.go
  pkg/spi/spi_mock.go
  pkg/spi/spi_test.go
Labels: lgtm

#105 Fix wrong link to e2e installation
  .ci/oci-e2e-has.sh
Labels: lgtm
