Repository redhat-appstudio/application-service, pull requests merged in 2023-06, with the labels that each got.

#331 Add Pact tests and job running them.
  .github/workflows/pr.yml
  Makefile
  codecov.yml
  controllers/application_pact_test.go
  controllers/application_pact_test_state_handlers.go
  controllers/application_pact_test_utils.go
  controllers/start_test_env.go
  controllers/suite_test.go
  go.mod
  go.sum
  pkg/util/util.go
Labels: lgtm

#342 [DEVHAS-386] add OWNERS file
  OWNERS
Labels: lgtm

#337 [RHTAPBUGS-285] fix the invalid devfile but with dockerfile case
  controllers/componentdetectionquery_controller.go
  controllers/componentdetectionquery_controller_test.go
Labels: lgtm, approved

#321 [RHTAPBUGS-238] return the default revision in cdq spec
  controllers/componentdetectionquery_controller.go
  controllers/componentdetectionquery_controller_test.go
  pkg/github/mock.go
Labels: lgtm, approved

#340 [DEVHAS-381] Don't panic when route's spec.Port is nil
  pkg/devfile/devfile.go
  pkg/devfile/devfile_test.go
Labels: approved

#341 [RHTAPBUGS-267]add retry on conflict in component controller
  controllers/component_controller.go
Labels: lgtm, approved

#335 [DEBHAS-358] do not return error if no component detected
  controllers/componentdetectionquery_controller.go
  controllers/componentdetectionquery_controller_conditions.go
  controllers/componentdetectionquery_controller_conditions_test.go
  controllers/componentdetectionquery_controller_test.go
  pkg/devfile/detect.go
  pkg/devfile/detect_mock.go
Labels: lgtm, approved

#345 Add instructions for installing pact for tests
  README.md
Labels: lgtm, approved

#344 [DEVHAS-377] update push.yaml for all deployment environments
  .tekton/push.yaml
  config/manager/feature_flag.properties
  config/manager/kustomization.yaml
Labels: lgtm, approved

#334 [DEVHAS-292] Use tini to manage zombie processes
  Dockerfile
  Makefile
  config/manager/manager.yaml
  entrypoint.sh
Labels: lgtm, approved

#347 Add Pact post-merge job
  .github/workflows/pact_postmerge.yml
  controllers/application_pact_test.go
Labels: lgtm, approved

#349 [DEVHAS-374] update HAS rate limiting metrics dashboard
  config/monitoring/grafana-dashboards/has-rate-limiting-metrics.json
Labels: lgtm, approved

#348 Ensure generated route names are unique and don't change
  .gitignore
  controllers/applicationsnapshotenvironmentbinding_controller.go
  controllers/applicationsnapshotenvironmentbinding_controller_test.go
  controllers/start_test_env.go
  go.mod
  go.sum
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved

#352 [RHTAPBUGS-435] ensure args from pod get passed into entrypoint
  entrypoint.sh
Labels: lgtm, approved

#351 [DEVHAS-398] Component name generation update
  controllers/componentdetectionquery_controller.go
  controllers/componentdetectionquery_controller_test.go
  controllers/update.go
  controllers/update_test.go
Labels: lgtm, approved

#356 Add log statements for SEB route name
  controllers/applicationsnapshotenvironmentbinding_controller.go
Labels: approved

#354 Update local test execution flow.
  Makefile
  controllers/application_pact_test.go
Labels: lgtm, approved

#355 [RHTAPBUGS-442] Properly clean up cloned repositories in error states
  controllers/component_controller.go
  controllers/componentdetectionquery_controller.go
  pkg/util/ioutils/ioutils.go
  pkg/util/ioutils/ioutils_test.go
Labels: approved

#353 [RHTAPBUGS-441]make changes to random chars
  controllers/componentdetectionquery_controller_test.go
  controllers/update.go
  controllers/update_test.go
  go.mod
  go.sum
Labels: lgtm, approved
