Repository redhat-appstudio/application-service, pull requests merged in 2023-11, with the labels that each got.

#407 [DEVHAS-493]update library version
  cdq-analysis/go.mod
  cdq-analysis/go.sum
  go.mod
  go.sum
Labels: lgtm, approved

#408 Error when configmap cannot be found
  controllers/componentdetectionquery_controller.go
Labels: approved

#409 [RHTAPBUGS-824] Don't overwrite probe ports if they are already set
  pkg/devfile/devfile.go
  pkg/devfile/devfile_test.go
Labels: lgtm, approved

#412 [DEVHAS-549]remove clonepath after cdq is done
  cdq-analysis/pkg/componentdetectionquery.go
  cdq-analysis/pkg/componentdetectionquery_test.go
Labels: lgtm, approved

#413 [DEVHAS-529] Update webhook to set nudged component's status when buildNudgesRef is set
  controllers/webhooks/component_webhook.go
  controllers/webhooks/component_webhook_test.go
  controllers/webhooks/component_webhook_unit_test.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: lgtm, approved

#402 Refactor pact tests
  contracts/application_pact_test.go
  contracts/application_pact_test_state_handlers.go
  contracts/pact_state_handlers_methods.go
  contracts/pact_state_params.go
  contracts/pact_states.go
  contracts/pact_test.go
  contracts/pact_utils.go
Labels: lgtm

#414 Update codecov ignore list - ignore token mock and contract test files
  codecov.yml
Labels: lgtm, approved

#411 [DEVHAS-490] Mocking CDQ Util for Private Repo Testing
  cdq-analysis/main.go
  cdq-analysis/pkg/componentdetectionquery.go
  cdq-analysis/pkg/componentdetectionquery_test.go
  cdq-analysis/pkg/detect.go
  cdq-analysis/pkg/detect_test.go
  cdq-analysis/pkg/devfile.go
  cdq-analysis/pkg/devfile_test.go
  cdq-analysis/pkg/mock.go
  codecov.yml
  controllers/componentdetectionquery_controller.go
  controllers/componentdetectionquery_controller_test.go
  controllers/start_test_env.go
  controllers/update.go
  controllers/update_test.go
  main.go
Labels: lgtm, approved

#410 [DEVHAS-488]annotation to force generate gitops
  controllers/application_controller_finalizer.go
  controllers/component_controller.go
  controllers/component_controller_conditions.go
  controllers/component_controller_test.go
Labels: lgtm, approved

#417 Fix finalize logging
  controllers/application_controller.go
Labels: lgtm, approved

#418 Get application in retry blocks
  controllers/application_controller.go
Labels: lgtm, approved

#416 Try to fix code coverage reporting
  .github/workflows/codecov.yml
  controllers/start_test_env.go
Labels: lgtm, approved

#419 Run make test on codecov upload
  .github/workflows/codecov.yml
Labels: lgtm, approved

#405 DEVHAS-237: Fail Pr codecov check when coverage drop by 2% the coverage
  .github/workflows/codecov.yml
  codecov.yml
Labels: lgtm, approved

#422 feat: add sonar cloud properties
  .sonarcloud.properties
Labels: lgtm, approved

#423 Fix deployment spec when replica set to 0
  pkg/devfile/devfile.go
  pkg/devfile/devfile_test.go
Labels: approved
