Repository redhat-appstudio/application-service, pull requests merged in 2023-09, with the labels that each got.

#384 DEVHAS-442: Add kube linter workflow
  .github/workflows/pr.yml
Labels: approved

#385 Update pact to v2 to support v3 schema
  .github/workflows/pact_postmerge.yml
  .github/workflows/pr.yml
  Makefile
  controllers/application_pact_test.go
  controllers/application_pact_test_state_handlers.go
  go.mod
  go.sum
Labels: lgtm, approved

#386 Private Repo Support
  cdq-analysis/go.mod
  cdq-analysis/go.sum
  cdq-analysis/main.go
  cdq-analysis/pkg/componentdetectionquery.go
  cdq-analysis/pkg/componentdetectionquery_test.go
  cdq-analysis/pkg/detect.go
  cdq-analysis/pkg/detect_test.go
  cdq-analysis/pkg/devfile.go
  cdq-analysis/pkg/devfile_test.go
  cdq-analysis/pkg/util.go
  cdq-analysis/pkg/util_test.go
  config/rbac/role.yaml
  controllers/application_controller.go
  controllers/application_controller_finalizer.go
  controllers/application_controller_finalizer_test.go
  controllers/application_controller_test.go
  controllers/applicationsnapshotenvironmentbinding_controller.go
  controllers/applicationsnapshotenvironmentbinding_controller_test.go
  controllers/component_controller.go
  controllers/component_controller_finalizer.go
  controllers/component_controller_finalizer_test.go
  controllers/component_controller_test.go
  controllers/componentdetectionquery_controller.go
  controllers/componentdetectionquery_controller_test.go
  controllers/start_test_env.go
  controllers/update.go
  controllers/update_test.go
  docs/private-git-repos.md
  go.mod
  go.sum
  main.go
  pkg/devfile/devfile.go
  pkg/devfile/devfile_test.go
  pkg/spi/spi.go
  pkg/spi/spi_mock.go
  pkg/spi/spi_test.go
Labels: lgtm, approved

#391 Refactoring Pact tests and adding parametrized states
  contracts/application_pact_test.go
  contracts/application_pact_test_state_handlers.go
  contracts/application_pact_test_utils.go
  controllers/application_pact_test_state_handlers.go
  controllers/start_test_env.go
  controllers/suite_test.go
Labels: lgtm

#388 [DEVHAS183] create kube jobs for CDQ analysis
  .tekton/push-cdq-analysis.yaml
  cdq-analysis/entrypoint.sh
  cdq-analysis/main.go
  cdq-analysis/pkg/componentdetectionquery.go
  cdq-analysis/pkg/componentdetectionquery_test.go
  cdq-analysis/pkg/devfile.go
  cdq-analysis/pkg/errors.go
  config/rbac/role.yaml
  controllers/componentdetectionquery_controller.go
  controllers/componentdetectionquery_controller_test.go
  controllers/start_test_env.go
  go.mod
  main.go
Labels: lgtm, approved

#392 Component metrics
  controllers/component_controller.go
  controllers/component_controller_finalizer_test.go
  pkg/metrics/metrics.go
Labels: lgtm, approved
